name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t bookvision:latest .

    - name: Tag Docker image
      run: docker tag bookvision:latest ${{ secrets.DOCKER_USER }}/bookvision:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/bookvision:latest

      


