name: Deployment to AWS EC2

on:
  workflow_run:
    workflows: ["Build and Deploy to Docker Hub"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKER_USER }}/bookvision:latest
    - name: Delete Old docker container
      run: sudo docker rm -f bookvision-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8501:8501 --name bookvision-container ${{ secrets.DOCKER_USER }}/bookvision
